/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Energy: typeof import('./src/components/dialog/Energy.vue')['default']
    LuckyWheel: typeof import('./src/components/home/LuckyWheel.vue')['default']
    MyProfile: typeof import('./src/components/home/MyProfile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharePage: typeof import('./src/components/home/SharePage.vue')['default']
    SimpleKeyboard: typeof import('./src/components/SimpleKeyboard.vue')['default']
    StartPage: typeof import('./src/components/startPage.vue')['default']
    Task: typeof import('./src/components/home/task.vue')['default']
    Toast: typeof import('./src/components/toast/toast.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanSticky: typeof import('vant/es')['Sticky']
    WithDraw: typeof import('./src/components/dialog/WithDraw.vue')['default']
  }
}
